name: Deploy to Vercel (Prod)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Packages
        run: npm install

      - name: Prisma migrate
        run: npx prisma db push
        env:
          # DATABASE_PRISMA_URL: ${{ secrets.DATABASE_PRISMA_URL }}
          # DATABASE_URL_NON_POOLING: ${{ secrets.DATABASE_URL_NON_POOLING }}
          DATABASE_PRISMA_URL: postgres://default:rpa5mEjk4Qof@ep-round-star-a1ev71aq-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require&pgbouncer=true&connect_timeout=15
          DATABASE_URL_NON_POOLING: postgres://default:rpa5mEjk4Qof@ep-round-star-a1ev71aq.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require


      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # - name: Pull Vercel Environment Information
      #   run: Vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Build Project
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Deploy Project to Vercel
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}